listen: :443

acme:
  domains:
    - random.drrr-sy.top
  email: hongsy2020@foxmail.com

auth:
  type: password
  password: 0CA78052-A8A6-46E7-A859-3D767614E8E6

masquerade:
  type: proxy
  proxy:
    url: https://www.microsoft.com
    rewriteHost: true
  listenHTTP: :80
  listenHTTPS: :443
  forceHTTPS: true

obfs:
  type: salamander
  salamander:
    password: 779BA00B-BBBC-454B-825A-18F22D26C37B 

